language: php
php:
  - 5.4
before_script: composer install
script: phpunit tests
deploy:
  provider: openshift
  user: asensi12887@iesmarenostrum.com
  password: mercuryteam
  app: php
  domain: mercuryteam
